### ISSUE TITLE
求助，按照文档使用没有效果

### ISSUE THREAD

**Issue by elowes** [luojilab/easy-marker#1]
[复现链接](https://codesandbox.io/s/14k6oorv2l)

**Comment by leaves4j** [comment]
我将尽快修复

**Comment by leaves4j** [comment]
@elowes 
[示例连接](https://codesandbox.io/s/x2zv4l8ln4)
[预览连接](https://x2zv4l8ln4.codesandbox.io/) (请用切换到手机模拟器）

**Comment by mozi0309** [comment]
@leaves4j thx，可以用了

**Comment by elowes** [comment]
尴尬，换了一台电脑，github登录的不是我的账号，刚刚才发现。
